### ISSUE TITLE
Sound problems UE 5.1

### ISSUE THREAD

**Issue by Denis-Semenovykh** [microsoft/ProjectAcoustics#180] opened 2023-08-09 09:16 UTC
Hello! When the Project Acoustics plug-in is enabled in the settings. When playing sounds that are positioned in 3d, 2d sounds (for example roomtones or VO) are interrupted or not played at all. What can be the reason? The spatialization plugin is also selected Project acoustics, but disabling it does not affect the situation. And there are no errors in log screen. Also sometimes when you switch the sound to binaural it stops spatializing, and sounds always in the center. If you return the value to panning, everything works. This applies to sounds in Soundscapes(Colours and sound pallet)

**Comment by NoelCross** [comment] 2023-08-09 19:11
@Denis-Semenovykh It's pretty difficult to know exactly why this is happening, but the first thing I'd check is to take a look at the Attenuation settings attached to each of these sounds to see if there are shared properties between the different sound types.

Also, this might be a stretch, but we are aware of an issue in the Google Resonance plugin that when enabled (but not necessarily used), there can be some negative side effects that impact other spatialization plugins.  This has been fixed recently, but it may not be in your version of UE.  If you do have Resonance enabled in the plugins window, please disable the plugin, restart your project and then see if your behavior changes.

Thanks,
Noel

**Comment by Denis-Semenovykh** [comment] 2023-08-10 08:31
@NoelCross   Hello Noel! Thank you for your reply! But it didn't help me and didn't change the situation. After looking more I realized that everything happens while the character is moving, when playing footsteps sound, less obvious on the walk mode, but on the run mode very clearly when the footsteps become more frequent. All the surrounding sounds begin to interrupt. If you put the steps in panning mode, everything works fine. Another thing, if you play sounds through play notify in animations, if they are in binaural mode and Ignore Attenuation is not checked, the sound is not played, again if you switch to panning mode everything works....
UPDATE- ....One more thing. I haven't baked the level yet, and I haven't placed Acoustic Space. But I have the SDO plugin enabled. And nowhere in the attenuations I have not specified it. And if I turn off the plugin in the settings, everything is fine. Maybe there is a conflict somewhere?
And another moment, if I change Spatial reverb quality from Best to Good all works fine. What does it mean?...Our team has pretty powerful computers)))))

**Comment by Denis-Semenovykh** [comment] 2023-08-11 08:47
And another one questions. I tried baking the data, on the pre-calculation everything is fine, the probes are aligned. But after baking, the coordinates of the bake zone in the ace file moved. I.e. probes and voxels in Acoustic Space are in a different place, not where they should be in the preliminary calculation. I baked not a large area locally, on my machine. Why could this happen?

**Comment by NoelCross** [comment] 2023-08-11 15:35
@Denis-Semenovykh this last reply has a clue about the behavior that might indicate what the problem is.  The Acoustics Space actor has the ability to be placed in the scene with an offset other than 0,0,0.  If the offset is anything other than 0,0,0, then you would be getting the strange behavior that you describe in your last reply.  Check the Acoustics Space actor to ensure there is no translation applied.

**Comment by Denis-Semenovykh** [comment] 2023-08-11 15:39
@NoelCross Hello, Noel! Got it, I'll look into it, thanks! What about my previous comment? The key note there is that all the problems went away as soon as we switched the Spatial Reverb quality to Good instead of Best. Why could this happen? We have quite powerful computers

**Comment by NoelCross** [comment] 2023-08-11 20:36
@Denis-Semenovykh it's unclear why the problems you are seeing are specific to the Best quality setting for spatial reverb.  One other thing to try is to see if choosing Stereo Convolution gives you a different experience that contrasts with the Spatial Reverb option.

Also, does this behavior happen on multiple machines with different audio adapters?  I'm curious if your hardware is exposing multi-channel output which might be a condition that wasn't handled properly.  This doesn't make sense because the Good vs. Best quality setting shouldn't matter when it comes to the number of output channels.

I'm not sure if you are able to share a video illustrating the behavior you are experiencing.  Ideally, turn on the debug visualizations so we can see what parameters are being applied for each sound source.

**Comment by Denis-Semenovykh** [comment] 2023-08-11 20:51
@NoelCross Yes, this problem happens on all our different computers. We do not use multi-channel outputs. I would be happy to provide a video, but unfortunately I can't, because it's a closed project, of course I'll talk to our management, maybe we'll find some solution for this. At the moment, tell me what I need to pay attention to? And this problem happens when the character moves, if you stand still, then even in Best mode everything is fine.

**Comment by NoelCross** [comment] 2023-08-11 21:36
@Denis-Semenovykh if you have a stripped down, generic version of the project with generic assets, that might be another way that we can investigate this issue.

When looking at the debug data, the arrival direction arrows from the sound sources is always a good indicator of what metadata is flowing through the system.  Also, looking at the wet/dry levels help give an indication of what the rendering DSP is attempting to render.  By turning on the debug visualizations, you might be able to identify why the rendering of a specific source is incorrect.

**Comment by Denis-Semenovykh** [comment] 2023-08-12 06:51
@NoelCross Hello! Choosing Stereo Convolution working fine, no bugs. This happens mostly with 2d sounds, roomtones and VOs. I recorded you audio, for more understanding, and brought out loud roomtone. The problems start when the character starts moving, and there are other 3d sounds that affect the 2d, if you stand there is nothing wrong. For example, you will hear when a source with music appears nearby, the roomtone starts to interrupt. Also there is an effect on VO, they are interrupted if you start moving. Nowhere does it show any errors. 

https://github.com/microsoft/ProjectAcoustics/assets/90043919/4a1c7813-6425-4527-affc-373f6b3f0659

**Comment by Denis-Semenovykh** [comment] 2023-08-14 17:47
@NoelCross Hello, again! We're facing another problem and it looks like the worst case scenario. The point is that our build is built on a Linux server. And during the build an error occurs, the plugin is not supported. We tried to bypass it, but nothing worked..As I understand this problem can not be solved, right? Or there are some ways?

**Comment by NoelCross** [comment] 2023-08-14 18:21
@Denis-Semenovykh I'm sorry to inform you that there is no Linux version of the plugin.  We only distribute versions of the binaries for Android and Windows in the UE Marketplace.  I assume that you are seeing linker issues with our runtime components.  If you are seeing something different than linker issues, I'm curious what build error you are seeing.

**Comment by Denis-Semenovykh** [comment] 2023-08-14 18:23
@NoelCross  Error: Failed to cook /Game/Maps/Game/TrainStation/SLs/SL_Train_station_audio for platform LinuxServer. It imports class /Script/ProjectAcoustics.AcousticsSpace, which is in a module that is not available on the platform.

**Comment by Denis-Semenovykh** [comment] 2023-08-14 18:23
LogCook: Error: Failed to cook /Game/Sounds/ProjectAcoustics/NewAcousticsSourceDataOverrideSourceSettings for platform LinuxServer. It imports class /Script/ProjectAcousticsNative.AcousticsSourceDataOverrideSourceSettings, which is in a module that is not available on the platform.

**Comment by Denis-Semenovykh** [comment] 2023-08-15 09:14
@NoelCross Hello! Wrote to you above, the errors we see. Is it possible to make solution so that linux dedicated server build without Project Acoustic? I.e. part of the classes should be placed in a module that has no platform restrictions. inside through preprocessor macros to divide the code so that if the platform is Windows or Android, the plugin is activated, and if another platform, the class is just empty. Is it possible to realize such a solution?

To be more specific, here's the deal :
The problem with plugin that it does not compile for Linux platform but game still has references to plugin. Even Linux is not supported and not required, we still need to have dedicated server for Linux.
The problem example is ProjectAcoustics.AcousticsSpace which is placed in map and when you are building linux server without ProjectAcoustics plugin – it get an error that AcousticsSpace is unknown class.
The other example is AcousticsSourceDataOverrideSourceSettings class which is added to sounds settings and when building linux server it again says that unknown class. Dedicated server does not require sound at all, but it should know all code classes it uses but ProjectAcoustics plugin is disabled for it so no classes are included in build. Even AcousticsSourceDataOverrideSourceSettings is based on class which is multiplatform class without platform restrictions.
You can create any project from UE template, add AcousticsSpace to map or sound asset to map which uses AcousticsSourceDataOverrideSourceSettings and try to build dedicated server for linux to see all errors.
What is possible to do:
1.	You can make one more module in ProjectAcoustics plugin without platform restrictions and add placeholder classes that added to map or to sound assets (like AcousticsSpace or AcousticsSourceDataOverrideSourceSettings).
2.	In that classes add code in platform macros #if PLATFORM_LINUX or maybe with #if UE_SERVER for dedicated server for any platform and leave inside this macros empty code, so class can compile empty because sounds are not required for dedicated server. And in #else section you can use code from plugin normally like it now so for other platform or not for server it will work as intended.
This is not a single solution possible, you may find your way.

**Comment by HDalsfelt** [comment] 2023-08-16 07:59
Agree with Denis that it would be great if you could at least compile on Linux by default. My solution was to make my own versions of some classes (e.g FAcousticsDesignParams, AcousticsInterpolationDisambiguationMode...) and add a lot of #if PLATFORM_LINUX to make the server builds to compile, but it won't be easy to upgrade PA the next time. :)

**Comment by Denis-Semenovykh** [comment] 2023-08-16 12:25
@HDalsfelt Hello! Yes, that's what I wrote about...could you send me a link to your version of the plugin, it's interesting to see and check your implementation.

**Comment by HDalsfelt** [comment] 2023-08-16 13:25
A lot of our code is incorporated into the game code so it's a bit hard to separate. But the big things (checking changesets) to get you started (have no idea if this is the best way):  

- Added a NeedsLoadForServer (returning false) in acousticdata/space so the server does not try to load the data.
- Added defines before all usage of PA-code and includes
    #if !UE_SERVER
    #if !PLATFORM_LINUX
- In the build.cs files added check for target platforms for the project acoustic plugins. E.g. in ProjectAcousticWwiseEditor.Build.cs

 if (Target.Platform == UnrealBuildTool.UnrealTargetPlatform.Win64)
        {
            PublicDependencyModuleNames.AddRange(
                new string[] {
                "ProjectAcoustics",
                "ProjectAcousticsWwise",
                }
            );
        }   

ProjectAcousticsBakeUI.Build.cs ->

if (Target.Platform == UnrealBuildTool.UnrealTargetPlatform.Win64)
        {
            PrivateIncludePaths.AddRange(
            new string[] {
                "../Source/ProjectAcoustics/Public"
                // ... add other private include paths required here ...
            }
            );

            PublicDependencyModuleNames.AddRange(
                new string[] {
                "ProjectAcoustics",
                }
            );
        }
etc.

- Added #include "AcousticsShared.h" in the acoustics .cpp files to make them compile in non-unity builds


Sooo, there's a start at least. I accidentally push to our main branch before I tested the linux-build so these fixes were made during a long evening with no design whatsoever... so I guess there might be better ways. =)

**Comment by Denis-Semenovykh** [comment] 2023-08-20 09:41
@NoelCross Hello! What do you think about it?

**Comment by NoelCross** [comment] 2023-08-21 20:36
@Denis-Semenovykh When it comes to building on Linux servers, we haven't had a customer that requested this configuration, so it is not something that we've tested.  If the changes suggested above gets you unblocked, then I don't see a problem with integrating those changes into your project.

For the issue with the 2d sound dropping out when selecting the Best quality spatial reverb, I'm still suspecting that the reverb processing is overloading the system.  The Best quality setting can take up to 20% of a system, so there might be some contention in the system for resources even on a high end machine.  A good test would be to bring up the Unreal profiler and see if threads are getting starved for processing during gameplay.  Another option for debugging would be to come up with a minimal repro project that exhibits the same problem and doesn't illustrate any of the secrets that you don't want to show.  We could diagnose this simple test project to see if we can identify the root cause.

**Comment by Denis-Semenovykh** [comment] 2023-08-22 07:15
@NoelCross Hello! If we integrate changes into a plugin in our project, won't there then be a problem updating it when you provide a new version? Maybe you can make such a feature on your side, so that it is present in the plugin by default, is it possible?

**Comment by NoelCross** [comment] 2023-08-22 17:05
@Denis-Semenovykh we currently don't have plans to update the plugin anytime soon, so best to make the changes on your end and clearly mark in comments where the changes are.  I don't expect that there will be too many conflicts if we update the plugin in the future with the changes you need to get working on Linux servers.

**Comment by Denis-Semenovykh** [comment] 2023-08-22 17:12
@NoelCross Thank you for your comments! We will try to integrate this solution in our project. If there are any questions I will write. And I was honored to communicate with you! 🙂

**Comment by KyleStorck** [comment] 2023-10-02 16:12
Closing. Feel free to reopen if you need further assistance.

**Closed as completed by KyleStorck** 2023-10-02 16:12 UTC
