### ISSUE TITLE
Download page says v1.1, packages say v1.0

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#8] opened 2019-12-06 02:18 UTC
The Project Acoustics download page https://www.microsoft.com/en-us/download/details.aspx?id=58090 says the download is for v1.1. 

The file sizes for the downloads approximately match the sizes given on the page.

ProjectAcousticsPlugins/Wwise/2019.1/ProjectAcoustics/bundle.json says version 1.0. 
ProjectAcousticsPlugins/Wwise/2018.1/ProjectAcoustics/bundle.json says version 1.0. 
ProjectAcousticsPlugins/Unreal/ProjectAcoustics/ProjectAcoustics.uplugin says version 1.0.

**Comment by MikeChemi** [comment] 2019-12-06 18:41
Hi borogove! Sorry for the versioning mismatch. This was caused by an error in setting the version metadata on some of our files. The plugins provided at the link you have are version 1.1, despite what some of the metadata says. We'll make sure to properly update these metadata files for our next release.

The Project Acoustics DLLs should be tagged with the correct version number. For example, in the ProjectAcousticsPlugins package, you should see that this DLL has a product version of 1.1: ProjectAcousticsPlugins\Wwise\2019.1\ProjectAcoustics\SDK_Windows_vc150\SDK\x64_vc150\Profile\bin\AcousticsWwiseDll.dll

**Comment by borogove** [comment] 2019-12-06 21:01
Cool, I just happened to notice the mismatch when I was trying to diagnose my build issue.

**Comment by kegodin** [comment] 2020-02-13 17:56
Tracked internally with VSO bug # 24288237. Resolved as fixed internally and expected to go out with next public release.

**Comment by MikeChemi** [comment] 2021-04-08 19:33
Fixed in version 2.0 #55

**Closed by MikeChemi** 2021-04-08 19:33 UTC
Labels: Fixed internally, Tracked internally, Unreal, Wwise, bug
