### ISSUE TITLE
Can't Install Plugin To Wwise 

### ISSUE THREAD

**Issue by jkoyote** [microsoft/ProjectAcoustics#83] opened 2022-03-31 18:38 UTC
I keep trying to install the Project Acoustics plugin to Wwise and keep getting the following error. (Installation failed. Error installing prerequisites: "Error: context.redistributables is not iterable") I'm using version 2019.2.14. of the Wwise launcher and the plugin downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=58090 

Any help or insight would be greatly appreciated!

**Comment by nikunjragh** [comment] 2022-03-31 18:52
Try putting the plugin package somewhere on C: (or whichever drive you have Wwise installed). We had someone report this same issue when installing over a network location with Wwise 2019.x.

**Comment by jkoyote** [comment] 2022-03-31 18:57
Thank you! I just tried that and received the same error.

**Comment by haisting** [comment] 2022-04-03 07:15
Just wanted to ping and say I'm having the same issue!

First, I get an error that says:

Invalid bundle.json; missing id member.

Then after hitting **Retry** I get this:

Installation failed. Error installing prerequisites: "Error: context.redistributables is not iterable"

**Comment by NoelCross** [comment] 2022-04-03 16:02
@jkoyote, @haisting, just a quick update on this issue.  We've confirmed this issue on our end and have reached out to AudioKinetic for assistance in diagnosing.  It appears that a recent change with the Wwise installers might have uncovered an issue with our plugin.  We'll let you know as soon as we have more information.

**Comment by jkoyote** [comment] 2022-04-04 12:44
Noel,

Thanks for checking into this. I’m eager to start working with Project Acoustics.

Josh

**Comment by john-tennant-sjs** [comment] 2022-04-05 18:04
Hello everyone, I just thought I'd chime in to say that I'm getting the same error here as everyone else. I'm relieved you guys are already working on a fix. Cheers!

**Comment by jkoyote** [comment] 2022-04-22 20:08
@NoelCross Any update on this?

**Comment by NoelCross** [comment] 2022-04-26 14:28
AudioKinetic has informed Microsoft that there will be a launcher update that should be out in the next few days that will address this.  Also, for the brave, you can manually copy the files from the Project Acoustics Wwise plugin package into the Wwise platform directories and get it to work, but the plugin won't be displayed in the launcher as being installed.  While in Wwise, the plugin will be visible.

**Comment by max-johnson** [comment] 2022-04-26 21:21
So glad to hear! Thanks all!

**Comment by NoelCross** [comment] 2022-05-03 22:01
@jkoyote @maxwell-johnson @john-tennant-sjs @haisting
We just received word from AudioKinetic on an update to the Wwise Launcher that is now out.  This update does indeed fix the problem that we were seeing with the integration of the Project Acoustics plug-in.  Let us know if you have any problems getting this to work with the latest launcher.

**Comment by jkoyote** [comment] 2022-05-04 14:24
Thanks for the update! I'm downloading the new version now.

**Comment by MikeChemi** [comment] 2022-05-19 16:44
Hey all, closing this one out since the current latest Wwise launcher no longer has the install issue. Please let us know if you hit anything similar again.

**Closed by MikeChemi** 2022-05-19 16:44 UTC
Labels: bug, Wwise
